highlighter: pygments
paginate: 4
paginate_path: "/blog/page:num/"
lsi: false
project-imgs: assets/img/project
permalink: /blog/:title
exclude: [README.md, .gitignore]

about:
  name: Kevin Zhou
  email: kevin@congeecafe.com
  about-line1: "Computer science student at U Waterloo."
  about-line2: "Former software developer at TD Lab."
  site-repo: CongeeCafe/CongeeCafe.github.io
  
external:
  github: CongeeCafe
  stackoverflow: 3408377/congeecafe
