highlighter: pygments
paginate: 4
lsi: false
exclude: [README.md, .gitignore]

about:
  name: Kevin Zhou
  email: kzhou@live.ca
  quickabout: "A Computer Science student at the University of Waterloo"
  
external:
  github: CongeeCafe
  stackoverflow: 3408377/congeecafe
